### PR TITLE
Address differences between `iso` and `clone` regarding disk creation.

### LINKED ISSUE #145: Unused raw disk
#### Overview of the Issue

When creating Packer build with latest version, a new disk is created which is unused. 

#### Reproduction Steps

```hcl
  disks {
    disk_size = "${var.vm_disk_size}"
    format = "${var.vm_format}"
    storage_pool = "${var.vm_storage_pool}"
    storage_pool_type = "${var.vm_storage_pool_type}"
    type = "${var.vm_type}"
    cache_mode = "${var.vm_cache_mode}"
    io_thread = "${var.vm_io_thread}"
  }
```

image

### Plugin and Packer version

Packer v1.8.5
Plugin v1.1.1

### Simplified Packer Buildfile

Packer build:
https://paste.modem7.com/62MoM-pWJrI

Packer variables:
https://paste.modem7.com/xLNnK-mbfw7

### Logs
`PACKER_LOG=1` does not give any additional information beyond:
```
❯ packer build .
ubuntu-server-jammy.proxmox-iso.ubuntu-server-jammy: output will be in this color.

==> ubuntu-server-jammy.proxmox-iso.ubuntu-server-jammy: Creating VM
==> ubuntu-server-jammy.proxmox-iso.ubuntu-server-jammy: No VM ID given, getting next free from Proxmox
==> ubuntu-server-jammy.proxmox-iso.ubuntu-server-jammy: Starting VM
==> ubuntu-server-jammy.proxmox-iso.ubuntu-server-jammy: Starting HTTP server on port 8811
==> ubuntu-server-jammy.proxmox-iso.ubuntu-server-jammy: Waiting 10s for boot
```

### Operating system and Environment details

Ubuntu 22.04.1 x64

### PR DESCRIPTION
**Pull request by sebastian-de**
The new `efi_config` brought differences between `iso` and `clone` to light.
The first difference is that `iso` will create the EFI disk in the first run and the additional call of `SetVmConfig` is not needed.
The second one is that `clone` will replace disks that are already present on the cloned VM with the ones specified in the builder configuration.

I addressed both differences in separate commits.

Closes #145

### CODE REVIEW

File: builder/proxmox/common/step_finalize_template_config.go [hunk 1]
```diff
@@ -105,6 +99,17 @@ func (s *stepFinalizeTemplateConfig) Run(ctx context.Context, state multistep.St
 		}
 	}
 
+	// Disks that get replaced by the builder end up as unused disks -
+	// find and remove them.
+	rxUnused := regexp.MustCompile(`^(unused)\d+`)
```
Comment (lbajolet-hashicorp) [inline builder/proxmox/common/step_finalize_template_config.go:104]: Unless you're using the regexp to extract things, I'd think the parentheses are not useful here

**Review by lbajolet-hashicorp — APPROVED** [review]
Hi @sebastian-de,

Just left a small suggestion regarding the regexp you defined to figure out which disks are unused, but aside from that LGTM!

**Comment by sebastian-de** [comment]
Hey @lbajolet-hashicorp,
I included your suggestion regarding the regex.
As always many thanks for the review!

**Comment by lbajolet-hashicorp** [comment]
My pleasure, thanks again for the effort you're pushing towards improving this plugin @sebastian-de, we really appreciate the involvement here, kudos to you!
